### PR TITLE
2nd PR to fix issue 45 (and others)

### PR DESCRIPTION
**Pull request by mattsaxon**
@beveradb, here's my second PR.

I acknowledge is is very large and not easy to review in GitHub compare. As I mentioned before, I'd be happy to try to split this up, if you'd like, but regardless I though you might like to look across the whole thing before we decide how to proceed.

This PR has 3 notable enhancements;

1. Cleanup shutdown code (to stop HA from hanging due to task cancellation - this is relatively discrete change and is mainly in the shutdown_loop() method with a couple of other changes (one in switch to add a specific task, the other in the init() function to setup the loop and store the tasks. This would be fairly easy to separate as a single PR if you would prefer.

2. Create retry logic throughout to deal with disconnect and other failures. This keeps the tasks running throughout these in "HA mode" and allows failure in CLI mode

3. Add functionality to deal with state maintenance. This is mostly moving away from flags to asyncio.events and also the addition of a functional availability property for HA such that the UI shows unavailable during issue. When availability is recovered, the module will reapply any pending state change also. (this needs an update to the HA wrapper module, which I will submit as another PR is a moment)

These last 2 changes are somewhat interdependent and they would be harder for me to pull apart (but I will still do so if you would prefer).

Once again sorry for the large PR and it will be the last time it happens, I'll start doing regular commits for anything I work on as I'm in a better position of knowledge now.

Lastly, very happy to work on any code styling issues, too large methods, other refactors etc...... don't be afraid to critique!

### CODE REVIEW

**Comment by mattsaxon** [comment]
OK, looks like my next learning curve it to write some automated tests for this!

**Comment by beveradb** [comment]
I've had a quick skim through and this looks good, but I'd want to check out the branch and test myself, give it a more thorough review before merging and tagging a release.

Keen to avoid duplicating efforts though, so I'll only do that when you tell me you're finished and it's good to go in your opinion if that's ok?

Thanks again for your work on this!

**Comment by mattsaxon** [comment]
Tested overnight and pretty successful. This is where I've had most issues, where lack of use leads to disconnections which need to wait till next use of switch to recover (which makes morning turn on less responsive)

All the issues were recovered on first or second attempt. I had a mixture of missed pongs and connections reset by peer. I had a total around 12 failure across 14 switches in the 12 hour period. They do seem to be located at specific times, so suspect its my wifi network that is causing the issues.

Anyway, I think its ready for you to look over. My only other pending change is a small change to reduce the number of warning in the error log on prolonged failure (as per the HA guidelines for a Silver level service). I can also commit this if your prefer, but you might quite like the greater number of warnings whilst testing!

**Comment by mattsaxon** [comment]
Overnight testing went well with around 12 failures, all of which automatically recovered at first or second attempt. 

I've only got a small additional commit to make which is to reduce the number of warnings during a prolonged disconnect. I can commit this now if you'd prefer, but I thought during testing you might like the additional warning which will be easier to spot.

I do however note that one of the changes is not compiling on Py3.5, this is a direct copy from WS7, so not sure how that is compiling!

**Comment by mattsaxon** [comment]
I note that the 3.5 build is failing and on checking, WS7 has dropped support for 3.5. Another reason that we can't upgrade tot full WS7! Anyway code fix looks fairly trivial, so let me just fix that before you crack on with review.

**Pull request merged**
